### ISSUE TITLE
Re-license under GPLv3

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/libsignal-protocol-rs#14]
Taking a deeper look at the [libsignal-protocol-c](https://github.com/signalapp/libsignal-protocol-c/tree/7bd0e5fee0ebde15c45fffcd631b74d188fd5551#license) README, it seems that their project is licensed under the GPLv3. 

At the moment we only have a couple contributors, so it should be easy enough to ask all contributors for permission to switch from a MIT/Apache-2.0 dual license to GPLv3.

Are the following people okay with relicensing?

- [x] @Michael-F-Bryan 
- [x] @shekohex

**Comment by shekohex** [comment]
I have no problem with GPLv3 At all.

**Comment by bmintz** [comment]
The readme badges still indicate MIT / Apache 2.0
