### ISSUE TITLE
Using Platform Native `CryptoProvider` 

### ISSUE THREAD

**Issue by shekohex** [Michael-F-Bryan/libsignal-protocol-rs#2]
I would suggest to use the native (platform provided) crypto api for the `CryptoProvider`

That means using 
#### By operating system:
 - OS X: [CommonCrypto](https://crates.io/crates/commoncrypto)
 - Linux/BSD/etc.: [OpenSSL](https://crates.io/crates/openssl) ( as a fallback too?)
 - Windows: [CryptoAPI](https://crates.io/crates/winapi) (maybe we just use openssl?)

I could start working on that, but i need some monitoring :smiley:

**Comment by Michael-F-Bryan** [comment]
I agree. We should probably provide n interface to the current platform's crypto API. Probably also provide a pure-Rust fallback for convenience (testing, examples, making compilation easier, etc).

At the moment I'm still in the process of wrapping the underlying C library so a lot of the design is still in flux, but if you'd like to get started on an initial implementation (e.g. for your operating system) I'd be more than happy to mentor!

**Comment by shekohex** [comment]
It seems to be that idea is not the best to do, instead having every implementation behind a feature flags works very well.
So i will close this now.
