### ISSUE TITLE
Exception Safety

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/libsignal-protocol-rs#33]
Up to now I've (deliberately) ignored the possibility that our code can panic while being called from C. For example, what would happen if the `PreKeyStore`'s `store()` method panicked [here][1]?

All of our "trampoline" functions need to deal with the possibility of panics. This should mostly be fixed by wrapping calls in a `std::panic::catch_unwind()`, but we may also want to require that *all* trait objects which are passed to C must implement `std::panic::RefUnwindSafe`. 

Alternatively, we could leave them as-is and add some sort of "poisoning" mechanism to the various [`State`][2] types. This would mean the first panic puts a `State` in a "poisoned" state and all further calls result in `InternalError::Unknown` (or some other suitable error).

[1]: https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/ca619c8a95fb3f4f4b2e09b3e32d6f04ae69fd69/libsignal-protocol/src/pre_key_store.rs#L56-L71
[2]: https://github.com/Michael-F-Bryan/libsignal-protocol-rs/blob/ca619c8a95fb3f4f4b2e09b3e32d6f04ae69fd69/libsignal-protocol/src/pre_key_store.rs#L35

**Comment by shekohex** [comment]
I'm a little bit confused about that, shall we use some sort of mechanism to check that our code almost panic-free, something like [`no-panic`](https://crates.io/crates/no-panic)? that could help in compile-time checking!

another side of that, already all of our C bridge functions has at least one `assert!(...)` which will panic if the `ptr` is null, so using `catch_unwind` for every c bridge function seems a good solution for that.

**Comment by Michael-F-Bryan** [comment]
> shall we use some sort of mechanism to check that our code almost panic-free, something like no-panic? that could help in compile-time checking!

I don't think we'll be able to have compile-time checking. We're using dynamic dispatch (boxed trait objects), which means we deliberately defer figuring out what code will be executed until runtime.

It might be a good idea to replace our `assert!(!foo.is_null())` calls with a custom macro (e.g. `signal_assert!()`) which will print a stack trace then *abort* if the assertion fails. That way we kill the entire program instead of accidentally unwinding into C.

Another option would be for the assertions to return `InternalError::Unknown.code()` early. That would mean we don't unwind and subtly break the world, but it then becomes the caller's (`libsignal-protocol-c`) responsibility to handle those errors...

**Comment by shekohex** [comment]
> It might be a good idea to replace our assert!(!foo.is_null()) calls with a custom macro (e.g. signal_assert!()) which will print a stack trace...

I think now we have logging on any errors of type (`InternalError:Unknown`) also with supported back-trace that we can easily debug.
