### ISSUE TITLE
Consider removing Cargo.lock

### ISSUE THREAD

**Issue by rubdos** [Michael-F-Bryan/libsignal-protocol-rs#55]
[The Rust FAQ seems to recommend](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) to *not* check in `Cargo.lock` in library projects.

Either way, with your permission, I'll send in a PR with dependency updates, because in my end-application I find quite a few duplicated dependencies by now :-)

**Comment by Michael-F-Bryan** [comment]
Sounds like a good idea to me :+1:
